services:
  nginx1:
    container_name: nginx1
    image: nginx
    ports:
      - "8001:8001"
    networks:
      - nginx1
    volumes:
      - ./nginx/nginx1.conf:/etc/nginx/conf.d/default.conf:ro

  nginx2:
    container_name: nginx2
    image: nginx
    ports:
      - "8002:8002"
    networks:
      - nginx2
    volumes:
      - ./nginx/nginx2.conf:/etc/nginx/conf.d/default.conf:ro

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    expose:
      - 3000
    networks:
      - nginx1
      - nginx2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx1:8001"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
    nginx1:
        driver: bridge

    nginx2:
        driver: bridge

volumes:
  grafana_data: